### ISSUE TITLE
Problems on "Ray"

### ISSUE THREAD

**Issue by cxwong919** [erizmr/taichi_ray_tracing#1]
I have this problem by running this code:

> UserWarning: Calling non-taichi function "Ray". Scope inside the function is not processed by the Taichi AST transformer. The function may not work as expected. Proceed with caution! Maybe you can consider turning it into a @ti.func?
  return Ray(self.cam_origin[None], self.cam_lower_left_corner[None] + u * self.cam_horizontal[None] + v * self.cam_vertical[None] - self.cam_origin[None])

> UserWarning: Calling non-taichi function "Ray". Scope inside the function is not processed by the Taichi AST transformer. The function may not work as expected. Proceed with caution! Maybe you can consider turning it into a @ti.func?

>  is_hit, hit_point, hit_point_normal, front_face, material, color = scene.hit(Ray(scattered_origin, scattered_direction))

My Taichi version is 1.4.0

Is there any solution to this problem?

Best regards!

**Comment by erizmr** [comment]
Hi @cxwong919 , thanks for reporting this. I have update the Ray to a dataclass and there should no warnings anymore. Please check the latest master branch.

**Comment by cxwong919** [comment]
@erizmr Thank you very much! And thank you for this great work.
